In [1]:
import torch

**此处为torch,~~虽然包叫pytorch~~**

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

张量：数组，但里面的内容都是数值，维度不限

In [3]:
x.shape

torch.Size([12])

通过`shape`可以查询张量的形状;[]代表维度为1，12代表这一维度的长度

In [4]:
x.numel()

12

`numel()`可以访问张量中元素的总数

In [5]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

通过`reshape(c,r)`,可以将张量重新排列成多维形式

In [6]:
y = x.reshape(4, 4)
y

RuntimeError: shape '[4, 4]' is invalid for input of size 12

但重组时，col*row必须等于元素总数

In [7]:
z = torch.zeros((2, 3, 4))
o = torch.ones((3, 2, 4))
print(z, '\n' ,o)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


使用`zeros()`构造全0矩阵，同理`ones()`, ~~没有除了1和0之外的数~~

In [8]:
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

使用`tensor()`手动构造变量