## 2.1 数据处理

In [1]:
import torch

**此处为torch,~~虽然包叫pytorch~~**

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

张量：数组，但里面的内容都是数值，维度不限

In [3]:
x.shape

torch.Size([12])

通过`shape`可以查询张量的形状;[]代表维度为1，12代表这一维度的长度

In [4]:
x.numel()

12

`numel()`可以访问张量中元素的总数

In [5]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

通过`reshape(c,r)`,可以将张量重新排列成多维形式

In [6]:
y = x.reshape(4, 4)
y

RuntimeError: shape '[4, 4]' is invalid for input of size 12

但重组时，col*row必须等于元素总数

In [7]:
z = torch.zeros((2, 3, 4))
o = torch.ones((3, 2, 4))
print(z, '\n' ,o)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


使用`zeros()`构造全0矩阵，同理`ones()`, ~~没有除了1和0之外的数~~

In [8]:
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

使用`tensor()`手动构造变量

In [9]:
torch.randn(3, 4)

tensor([[-0.2559,  0.4066,  0.4201, -1.1634],
        [-2.0670,  0.6678,  0.9912,  0.2923],
        [ 0.2710,  1.9265, -1.6423, -0.9642]])

生成随机数张量，元素平均数为0，标准差为1的正态分布中随机采样

### 运算符

In [10]:
x = torch.tensor([1.0,2, 4, 8])
y = torch.tensor([2,  3, 4, 5])
x+y,x-y,x*y,x/y,x**y,x%y

(tensor([ 3.,  5.,  8., 13.]),
 tensor([-1., -1.,  0.,  3.]),
 tensor([ 2.,  6., 16., 40.]),
 tensor([0.5000, 0.6667, 1.0000, 1.6000]),
 tensor([1.0000e+00, 8.0000e+00, 2.5600e+02, 3.2768e+04]),
 tensor([1., 2., 0., 3.]))

对于相同形状的张量，可以通过(+,-,*,/,%)作运算，具体来说：$I+J \rightarrow I_i+J_i$

In [11]:
import numpy

x = torch.tensor([numpy.e,numpy.log(2),1,torch.e])
torch.exp(x)

tensor([15.1543,  2.0000,  2.7183, 15.1543], dtype=torch.float64)

exp()求解e的x次方：$y_i=e^{x_i}$

In [12]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0), torch.cat((x,y),dim=1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

通过`cat()`可以实现拼接，`dim=0`按照行，`dim=1`按列

In [13]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2,1,4],[1,2,3],[4,3,2]])
torch.cat((x,y),dim=0), torch.cat((x,y),dim=1)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 4 but got size 3 for tensor number 1 in the list.

若尺寸不对应则会报错

In [14]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

近似于求位与运算

In [15]:
x = torch.arange(12).reshape((3,4))
torch.sum(x), x.sum()

(tensor(66), tensor(66))

元素求和

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

广播机制

In [17]:
x = torch.tensor([ [ [1],[1],[1] ] ,[[2],[3],[4] ] ])
y = torch.tensor([ [ [1,2,3]] ])
x,y,x+y

(tensor([[[1],
          [1],
          [1]],
 
         [[2],
          [3],
          [4]]]),
 tensor([[[1, 2, 3]]]),
 tensor([[[2, 3, 4],
          [2, 3, 4],
          [2, 3, 4]],
 
         [[3, 4, 5],
          [4, 5, 6],
          [5, 6, 7]]]))

试试多维，有点废脑子

In [18]:
x = torch.arange(12).reshape((3,4))
x,x[-1],x[2],x[0:2],x[0:3],x[0:-1],x[:-1],x[:],x[:0]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([ 8,  9, 10, 11]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([], size=(0, 4), dtype=torch.int64))

按行切片

In [19]:
x = torch.arange(12).reshape((3,4))
x[:,1] , x[1:3,1:] , x[0::2,1::2], x[0::2,0::2]

(tensor([1, 5, 9]),
 tensor([[ 5,  6,  7],
         [ 9, 10, 11]]),
 tensor([[ 1,  3],
         [ 9, 11]]),
 tensor([[ 0,  2],
         [ 8, 10]]))

`a:b:c`,在区间[a,b)中取数，step=c,a,c默认为0，b默认最后一位

In [20]:
x[1, 2] = 9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

暴力写入

In [21]:
y = torch.arange(4)
before = id(y)
y = y + x
id(y) == before

False

在处理变量中，一般操作会导致新建内存，如果矩阵数据特别大，容易消耗内存,可以使用原地存储

In [22]:
y = torch.arange(4)
before = id(y)
y += x
id(y) == before

RuntimeError: output with shape [4] doesn't match the broadcast shape [3, 4]

In [23]:
y = torch.arange(4)
x = torch.arange(4,8,1)
z = torch.zeros_like(y)
print('id(z):',id(z))
z[:] = x + y
print('id(z):',id(z))

id(z): 140157950377472
id(z): 140157950377472


Pytorch与Numpy的互换

In [24]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转化为python标量

In [25]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)